// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Movie
 */
export type Movie = {
    /**
     * Movieid
     */
    movieId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Year
     */
    year: number;
    /**
     * Genre
     */
    genre: Array<string>;
    /**
     * Description
     */
    description: string;
    /**
     * Posterurl
     */
    posterURL: string;
    /**
     * Letterboxdurl
     */
    letterboxdURL: string;
    /**
     * Trailerid
     */
    trailerID: string;
    /**
     * Similarityscore
     */
    similarityScore: number;
};

/**
 * Status
 */
export enum Status {
    STARTING = 'Starting.',
    VALIDATING_USERNAME = 'Validating username.',
    FAILED_INVALID_USERNAME = 'Failed invalid username.',
    WAITING_FOR_SCRAPER = 'Waiting for scraper.',
    SCRAPING_THE_USER_REVIEWS = 'Scraping the user reviews.',
    FAILED_NO_RATINGS_AND_REVIEWS_TO_SCRAPE_FOR_THE_USER = 'Failed no ratings and reviews to scrape for the user.',
    FAILED_ERROR_WHILE_SCRAPING = 'Failed error while scraping.',
    PREPROCESSING_DATA = 'Preprocessing data.',
    FAILED_NO_DATA_AVAILABLE_ABOUT_THE_USER_RATED_AND_REVIEWS_MOVIES = 'Failed no data available about the user rated and reviews movies.',
    FINDING_RECOMMENDATIONS = 'Finding recommendations.',
    FAILED_NO_TRENDING_MOVIES_NOT_ALREADY_REVIEWED_ARE_AVAILABLE_FOR_RECOMMENDATION = 'Failed no trending movies not already reviewed are available for recommendation.',
    FINISHED = 'Finished.'
}

/**
 * UsernameRequest
 */
export type UsernameRequest = {
    /**
     * Username
     */
    username: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type InitSystemUsernamesPostData = {
    body: UsernameRequest;
    path?: never;
    query?: never;
    url: '/usernames/';
};

export type InitSystemUsernamesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InitSystemUsernamesPostError = InitSystemUsernamesPostErrors[keyof InitSystemUsernamesPostErrors];

export type InitSystemUsernamesPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type CheckStatusStatusGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Username
         */
        username: string;
    };
    url: '/status/';
};

export type CheckStatusStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckStatusStatusGetError = CheckStatusStatusGetErrors[keyof CheckStatusStatusGetErrors];

export type CheckStatusStatusGetResponses = {
    /**
     * Successful Response
     */
    200: Status;
};

export type CheckStatusStatusGetResponse = CheckStatusStatusGetResponses[keyof CheckStatusStatusGetResponses];

export type GetRecommendMoviesMoviesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Username
         */
        username: string;
    };
    url: '/movies/';
};

export type GetRecommendMoviesMoviesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecommendMoviesMoviesGetError = GetRecommendMoviesMoviesGetErrors[keyof GetRecommendMoviesMoviesGetErrors];

export type GetRecommendMoviesMoviesGetResponses = {
    /**
     * Response Get Recommend Movies Movies  Get
     *
     * Successful Response
     */
    200: Array<Movie>;
};

export type GetRecommendMoviesMoviesGetResponse = GetRecommendMoviesMoviesGetResponses[keyof GetRecommendMoviesMoviesGetResponses];
